# Homework 3  - Tryout pandas and numpy

 

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [1]:
import pandas as pd
data=pd.read_csv(".\data\ccp_current_csv.csv") #csv file from data directory is read and loaded in 'data'
print data

                 STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW        

### Reference: 
http://pythonhow.com/data-analysis-with-python-pandas/

### 3.1.a  what is its shape and what does that mean?

Shape property is used to know the number of rows and columns in the dataset.

In [4]:
from numpy import *
data.shape  # or shape(data)

(465, 27)

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [27]:
# Displays the rows in each 'QUADRANT'
data['QUADRANT'].value_counts() 

NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [78]:
# Operational use
import numpy as np
a=np.array(([1,2,3,4]), dtype=float)
b=np.array(([5,6,7,8]),dtype=float)
a+b

array([  6.,   8.,  10.,  12.])

In [49]:
# Functional use

a=array([1,2,3,4])
b=array([5,6,7,8])
c = np.add((a),(b), dtype=float )
c

array([  6.,   8.,  10.,  12.])

### 3.3.2 subtraction a-b

In [79]:
# Operational use

a=np.array(([1,2,3,4]), dtype=float)
b=np.array(([5,6,7,8]),dtype=float)
a-b

array([-4., -4., -4., -4.])

In [51]:
# Functional use

a=array([1,2,3,4])
b=array([5,6,7,8])
c = np.subtract((a),(b), dtype=float )
c

array([-4., -4., -4., -4.])

### 3.3.3 multiplication a*b

In [80]:
# Operational use

a=np.array(([1,2,3,4]), dtype=float)
b=np.array(([5,6,7,8]),dtype=float)
a*b

array([  5.,  12.,  21.,  32.])

In [53]:
# Functional use

a=array([1,2,3,4])
b=array([5,6,7,8])
c = np.multiply((a),(b), dtype=float )
c

array([  5.,  12.,  21.,  32.])

### 3.3.4 divsion a/b

In [81]:
# Operational use

a=np.array(([1,2,3,4]), dtype=float)
b=np.array(([5,6,7,8]),dtype=float)
a/b

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

In [55]:
# Functional use

a=array([1,2,3,4])
b=array([5,6,7,8])
c = np.divide((a),(b), dtype=float )
c

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

### 3.3.5 modulo  a%b

In [82]:
# Operational use

a=np.array(([1,2,3,4]), dtype=float)
b=np.array(([5,6,7,8]),dtype=float)
a%b

array([ 1.,  2.,  3.,  4.])

In [57]:
# Functional use

a=array([1,2,3,4])
b=array([5,6,7,8])
c = np.mod((a),(b), dtype=float )
c

array([ 1.,  2.,  3.,  4.])

### 3.3.6 power  a^b

In [83]:
# Operational use

a=np.array(([1,2,3,4]), dtype=float)
b=np.array(([5,6,7,8]),dtype=float)
a**b

array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

In [59]:
# Functional use

a=array([1,2,3,4])
b=array([5,6,7,8])
c = np.power((a),(b), dtype=float )
c

array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

## Homework 3.4
Find your own data and load it into a dataframe

In [60]:
import pandas as pd
data1=pd.read_csv(".\data\dataset.csv")
print data1

     Customer       State  Customer Lifetime Value Response  Coverage  \
0     BU79786  Washington              2763.519279       No     Basic   
1     QZ44356     Arizona              6979.535903       No  Extended   
2     AI49188      Nevada             12887.431650       No   Premium   
3     WW63253  California              7645.861827       No     Basic   
4     HB64268  Washington              2813.692575       No     Basic   
5     OC83172      Oregon              8256.297800      Yes     Basic   
6     XZ87318      Oregon              5380.898636      Yes     Basic   
7     CF85061     Arizona              7216.100311       No   Premium   
8     DY87989      Oregon             24127.504020      Yes     Basic   
9     BQ94931      Oregon              7388.178085       No  Extended   
10    SX51350  California              4738.992022       No     Basic   
11    VQ65197  California              8197.197078       No     Basic   
12    DP39365  California              8798.797003 

### Reference:
http://www.scan-support.com/help/sample-data-sets,
Automobile insurance customer information with the expected lifetime value of the customer.

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [61]:
# To retrive the names of all columns in the dataframe
data1.columns

Index([u'Customer', u'State', u'Customer Lifetime Value', u'Response',
       u'Coverage', u'Education', u'Effective To Date', u'EmploymentStatus',
       u'Gender', u'Income', u'Location Code', u'Marital Status',
       u'Monthly Premium Auto', u'Months Since Last Claim',
       u'Months Since Policy Inception', u'Number of Open Complaints',
       u'Number of Policies', u'Policy Type', u'Policy', u'Renew Offer Type',
       u'Sales Channel', u'Total Claim Amount', u'Vehicle Class',
       u'Vehicle Size'],
      dtype='object')

In [63]:
# This iloc method allows us to retrieve rows and columns by position
data1.iloc[:4,0]       # displays 4 rows for the first column

0    BU79786
1    QZ44356
2    AI49188
3    WW63253
Name: Customer, dtype: object

In [65]:
# This loc method allows us to retrieve columns by label instead of by position.
data1.loc[:5,["State","Customer"]]   # displays 5 rows for the specified column or column lists.

State Customer
0  Washington  BU79786
1     Arizona  QZ44356
2      Nevada  AI49188
3  California  WW63253
4  Washington  HB64268
5      Oregon  OC83172

In [72]:
data1.mean() # displays average values of the numerical values in each dataframe column 

Customer Lifetime Value           8004.940475
Income                           37657.380009
Monthly Premium Auto                93.219291
Months Since Last Claim             15.097000
Months Since Policy Inception       48.064594
Number of Open Complaints            0.384388
Number of Policies                   2.966170
Total Claim Amount                 434.088794
dtype: float64

In [77]:
# compares each value in Income column to a specified value(mean value of income), 
# then generate a Series full of Boolean values indicating the status of the comparison.
data1['Income']>37657

0        True
1       False
2        True
3       False
4        True
5        True
6        True
7       False
8       False
9       False
10      False
11      False
12       True
13       True
14       True
15      False
16      False
17      False
18       True
19       True
20       True
21      False
22      False
23      False
24      False
25       True
26      False
27      False
28       True
29       True
        ...  
9104     True
9105    False
9106    False
9107    False
9108    False
9109    False
9110    False
9111     True
9112     True
9113     True
9114     True
9115    False
9116    False
9117     True
9118     True
9119     True
9120    False
9121    False
9122    False
9123    False
9124     True
9125    False
9126    False
9127     True
9128     True
9129     True
9130    False
9131    False
9132    False
9133    False
Name: Income, Length: 9134, dtype: bool

In [71]:
data1.count() # counts the number of non-null values in each DataFrame column

Customer                         9134
State                            9134
Customer Lifetime Value          9134
Response                         9134
Coverage                         9134
Education                        9134
Effective To Date                9134
EmploymentStatus                 9134
Gender                           9134
Income                           9134
Location Code                    9134
Marital Status                   9134
Monthly Premium Auto             9134
Months Since Last Claim          9134
Months Since Policy Inception    9134
Number of Open Complaints        9134
Number of Policies               9134
Policy Type                      9134
Policy                           9134
Renew Offer Type                 9134
Sales Channel                    9134
Total Claim Amount               9134
Vehicle Class                    9134
Vehicle Size                     9134
dtype: int64

In [75]:
# Computes pairwise correlation of columns
# pearson-standard correlation coefficient
# Minimum number of observations, required per pair of columns.
data1.corr(method='pearson', min_periods=3)

Customer Lifetime Value    Income  \
Customer Lifetime Value                       1.000000  0.024366   
Income                                        0.024366  1.000000   
Monthly Premium Auto                          0.396262 -0.016665   
Months Since Last Claim                       0.011517 -0.026715   
Months Since Policy Inception                 0.009418 -0.000875   
Number of Open Complaints                    -0.036343  0.006408   
Number of Policies                            0.021955 -0.008656   
Total Claim Amount                            0.226451 -0.355254   

                               Monthly Premium Auto  Months Since Last Claim  \
Customer Lifetime Value                    0.396262                 0.011517   
Income                                    -0.016665                -0.026715   
Monthly Premium Auto                       1.000000                 0.005026   
Months Since Last Claim                    0.005026                 1.000000   
Months Since Policy Inception              0.020257                -0.042959   
Number of Open Complaints                 -0.013122                 0.005354   
Number of Policies                        -0.011233                 0.009136   
Total Claim Amount                         0.632017                 0.007563   

                               Months Since Policy Inception  \
Customer Lifetime Value                             0.009418   
Income                                             -0.000875   
Monthly Premium Auto                                0.020257   
Months Since Last Claim                            -0.042959   
Months Since Policy Inception                       1.000000   
Number of Open Complaints                          -0.001158   
Number of Policies                                 -0.013333   
Total Claim Amount                                  0.003335   

                               Number of Open Complaints  Number of Policies  \
Customer Lifetime Value                        -0.036343            0.021955   
Income                                          0.006408           -0.008656   
Monthly Premium Auto                           -0.013122           -0.011233   
Months Since Last Claim                         0.005354            0.009136   
Months Since Policy Inception                  -0.001158           -0.013333   
Number of Open Complaints                       1.000000            0.001498   
Number of Policies                              0.001498            1.000000   
Total Claim Amount                             -0.014241           -0.002354   

                               Total Claim Amount  
Customer Lifetime Value                  0.226451  
Income                                  -0.355254  
Monthly Premium Auto                     0.632017  
Months Since Last Claim                  0.007563  
Months Since Policy Inception            0.003335  
Number of Open Complaints               -0.014241  
Number of Policies                      -0.002354  
Total Claim Amount                       1.000000

In [76]:
# Generates descriptive statistics,excluding NaN values.Can be applied on single data frame column or on all columns. 
data1.describe()

Customer Lifetime Value        Income  Monthly Premium Auto  \
count              9134.000000   9134.000000           9134.000000   
mean               8004.940475  37657.380009             93.219291   
std                6870.967608  30379.904734             34.407967   
min                1898.007675      0.000000             61.000000   
25%                3994.251794      0.000000             68.000000   
50%                5780.182197  33889.500000             83.000000   
75%                8962.167041  62320.000000            109.000000   
max               83325.381190  99981.000000            298.000000   

       Months Since Last Claim  Months Since Policy Inception  \
count              9134.000000                    9134.000000   
mean                 15.097000                      48.064594   
std                  10.073257                      27.905991   
min                   0.000000                       0.000000   
25%                   6.000000                      24.000000   
50%                  14.000000                      48.000000   
75%                  23.000000                      71.000000   
max                  35.000000                      99.000000   

       Number of Open Complaints  Number of Policies  Total Claim Amount  
count                9134.000000         9134.000000         9134.000000  
mean                    0.384388            2.966170          434.088794  
std                     0.910384            2.390182          290.500092  
min                     0.000000            1.000000            0.099007  
25%                     0.000000            1.000000          272.258244  
50%                     0.000000            2.000000          383.945434  
75%                     0.000000            4.000000          547.514839  
max                     5.000000            9.000000         2893.239678